/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_GestaoStock_v1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class JFrameAdicionarRemoverMaterialAmz extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInserirMaterialArmazem
     */
    public JFrameAdicionarRemoverMaterialAmz() {
        
        initComponents();
        setResizable(false);
        try{
            
            PopularComboBoxMaterial();
            PopularComboBoxArmazem();
        } 
        catch (Exception e){
            System.out.println("Erro ao Inicializar: " + e.getMessage());
        }
        
        
    }
    
    private void PopularComboBoxMaterial() 
    {
         jComboBoxIDMaterial.removeAllItems(); // Limpa todos os itens do ComboBox
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
             Statement stat = conn.createStatement()) {

            ResultSet resultadoQuery = stat.executeQuery("select id_material, nome from Material");

            while (resultadoQuery.next()) {
                String item = resultadoQuery.getString("id_material") + "-" + resultadoQuery.getString("nome");
                jComboBoxIDMaterial.addItem(item);
            }
        } catch (Exception e) {
            System.out.println("Erro ao popular combo box de Material: " + e.getMessage());
        }
    }
    
    private void PopularComboBoxArmazem() 
    {
        jComboBoxIDArmazem.removeAllItems(); // Limpa todos os itens do ComboBox
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
            Statement stat = conn.createStatement()) {

           ResultSet resultadoQuery = stat.executeQuery("select id_armazem, nome_amz from Armazens");

           while (resultadoQuery.next()) {
               String item = resultadoQuery.getString("id_armazem") + "-" + resultadoQuery.getString("nome_amz");
               jComboBoxIDArmazem.addItem(item);
           }
        } 
        catch (Exception e) {
            System.out.println("Erro ao popular combo box de Armazem: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonGravar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLocalizacao = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxIDArmazem = new javax.swing.JComboBox<>();
        jComboBoxIDMaterial = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Material no Armazem");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Localização Material:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Armazem:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Material:");

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxIDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLocalizacao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxIDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LimparCampos()
    {
       
        jTextFieldLocalizacao.setText("");
        jSpinner1.setValue(0);
        jComboBoxIDMaterial.setSelectedIndex(0);
        jComboBoxIDArmazem.setSelectedIndex(0);

        
    }
    
    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
        Statement stat = conn.createStatement()) {

            String idMaterial = jComboBoxIDMaterial.getSelectedItem().toString().split("-")[0];
            
            String idArmazem = jComboBoxIDArmazem.getSelectedItem().toString().split("-")[0];
            int quantidade = (int) jSpinner1.getValue();
            String localizacao = jTextFieldLocalizacao.getText();

            // Inserir novo registro na tabela Material_Armazem
            String insertQuery = "insert into Material_Armazem (id_material_amz, id_armazem_amz, quantidade,"
                    + " localizacao_material) values ('" + idMaterial + "', '" + idArmazem + "', " + quantidade +
                    ", '" + localizacao + "')";

            stat.executeUpdate(insertQuery);

            // Atualizar a quantidade disponível na tabela Material
            String updateQuery = "update Material set quantidade_disponivel = quantidade_disponivel + " + quantidade +
                    " where id_material = '" + idMaterial + "'";

            stat.executeUpdate(updateQuery);

            JOptionPane.showMessageDialog(this, "Quantidade do material foi inserida"
                    + " com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            LimparCampos();
            PopularComboBoxMaterial();
            jComboBoxIDArmazem.revalidate(); // Revalida a combobox para refletir as mudanças
            jComboBoxIDArmazem.repaint(); // Força a repintura da combobox para atualização visual
            PopularComboBoxArmazem();
            jComboBoxIDMaterial.revalidate();
            jComboBoxIDMaterial.repaint();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir"
                    + " quantidade do material: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            LimparCampos(); 
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
            PopularComboBoxMaterial();
            jComboBoxIDArmazem.revalidate(); // Revalida a combobox para refletir as mudanças
            jComboBoxIDArmazem.repaint(); // Força a repintura da combobox para atualização visual
            PopularComboBoxArmazem();
            jComboBoxIDMaterial.revalidate();
            jComboBoxIDMaterial.repaint();
            LimparCampos();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarRemoverMaterialAmz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarRemoverMaterialAmz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarRemoverMaterialAmz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarRemoverMaterialAmz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdicionarRemoverMaterialAmz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JComboBox<String> jComboBoxIDArmazem;
    private javax.swing.JComboBox<String> jComboBoxIDMaterial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldLocalizacao;
    // End of variables declaration//GEN-END:variables
}
