/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_GestaoStock_v1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ricardo
 */
public class JFrameListarMaterialArmazem extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListarMaterialAmerzem
     */

    public JFrameListarMaterialArmazem() {
        initComponents();
        setResizable(false);
        jComboBoxMatrialamz.enable(false);
        try {
            PopularComboBoxArmazem();
            
        } 
        catch (Exception e) {
            System.out.println("Erro ao Inicializar " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxIDArmazem = new javax.swing.JComboBox<>();
        jButtonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMatrialamz = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Material por Armazem");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Armazem:");

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matreial em Armazem");

        jComboBoxMatrialamz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMatrialamzActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade:");

        jLabelQuantidade.setForeground(new java.awt.Color(255, 255, 255));

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxMatrialamz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jLabelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMatrialamz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonAtualizar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        try {
            Atualiza();
            PopularComboBoxMaterialamz();
            
        } 
        catch (Exception e) {
            System.out.println("Erro ao Listar " + e.getMessage());
        }
        jComboBoxMatrialamz.enable(true);
        
        
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jComboBoxMatrialamzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMatrialamzActionPerformed
        try {
        atualizarQuantidadeTotal();
    } catch (Exception e) {
        System.out.println("Erro ao calcular quantidade total: " + e.getMessage());
    }
    }//GEN-LAST:event_jComboBoxMatrialamzActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        PopularComboBoxArmazem();
        jComboBoxIDArmazem.revalidate(); // Revalida a combobox para refletir as mudanças
        jComboBoxIDArmazem.repaint(); // Força a repintura da combobox para atualização visual
        jTextArea1.setText("");
        jLabelQuantidade.setText("");
    }//GEN-LAST:event_jButtonAtualizarActionPerformed
    
    private void PopularComboBoxArmazem() 
    {
         jComboBoxIDArmazem.removeAllItems(); // Limpa todos os itens do ComboBox
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
            Statement stat = conn.createStatement()) {

           ResultSet resultadoQuery = stat.executeQuery("select id_armazem, nome_amz from Armazens");

           while (resultadoQuery.next()) {
               String item = resultadoQuery.getString("id_armazem") + 
                       "-" + resultadoQuery.getString("nome_amz");
               jComboBoxIDArmazem.addItem(item);
           }
        } 
        catch (Exception e) {
            System.out.println("Erro ao popular combo box de Armazem: " + e.getMessage());
        }
    }
    
    private void Atualiza() throws Exception{
     
        try {
            
            String armazemEscolhido = jComboBoxIDArmazem.getSelectedItem().toString().split("-")[0].trim();
            
            Connection SQlCnn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/?user=root");  
            System.out.print("Ligação com sucesso");
            Statement stat1 = SQlCnn.createStatement();
            ResultSet resultadoQuery = stat1.executeQuery("Select ma.id_material_amz, m.nome, ma.quantidade,"
                    + " ma.localizacao_material From "
                + "BDGestaoStock.Material_Armazem ma "
                + "Inner Join BDGestaoStock.Material m On ma.id_material_amz = m.id_material "
                + "Where ma.id_armazem_amz = '" + armazemEscolhido + "'");

            String texto="";
              while( resultadoQuery.next()) 
                   texto= texto + resultadoQuery.getString("nome")
                           +"\t"+ resultadoQuery.getString("quantidade")
                           +"\t"+ resultadoQuery.getString("Localizacao_material")
                           +"\n";
        
              jTextArea1.setText(texto);
              resultadoQuery.close();
              stat1.close();
              SQlCnn.close();
        }
        catch (Exception CnnErr)
                     {
                     System.out.print("Mariadb Server - problema a autualizar lista de materiais no Armzem :"+CnnErr);
        }    
        
    }
    
    private void PopularComboBoxMaterialamz() 
    {
        jComboBoxMatrialamz.removeAllItems(); // Limpa todos os itens do ComboBox 
        
        String armazemEscolhido = jComboBoxIDArmazem.getSelectedItem().toString().split("-")[0].trim();
        
       
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
            Statement stat = conn.createStatement()) {

           ResultSet resultadoQuery = stat.executeQuery("Select ma.id_material_amz, m.nome, ma.quantidade, ma.localizacao_material From "
                + "BDGestaoStock.Material_Armazem ma "
                + "Inner Join BDGestaoStock.Material m On ma.id_material_amz = m.id_material "
                + "Where ma.id_armazem_amz = '" + armazemEscolhido + "'");

           while (resultadoQuery.next()) {
               String item = resultadoQuery.getString("nome")+ "-" + resultadoQuery.getString("quantidade");
               jComboBoxMatrialamz.addItem(item);
           }
        } 
        catch (Exception e) {
            System.out.println("Erro ao popular combo box de Material: " + e.getMessage());
        }
    }
    
    private void atualizarQuantidadeTotal() {
    if (jComboBoxMatrialamz.getSelectedItem() != null) {
        String selectedMaterial = jComboBoxMatrialamz.getSelectedItem().toString();
        String[] parts = selectedMaterial.split("-");
        String materialName = parts[0].trim(); // Nome do material

        int totalQuantity = 0;

        // Calcular a quantidade total do material selecionado
        String armazemEscolhido = jComboBoxIDArmazem.getSelectedItem().toString().split("-")[0].trim();
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/BDGestaoStock?user=root");
             Statement stat = conn.createStatement()) {

            ResultSet resultadoQuery = stat.executeQuery("Select ma.quantidade " +
                    "From Material_Armazem ma " +
                    "Inner Join Material m On ma.id_material_amz = m.id_material " +
                    "Where ma.id_armazem_amz = '" + armazemEscolhido + "' And m.nome = '" + materialName + "'");

            while (resultadoQuery.next()) {
                totalQuantity += resultadoQuery.getInt("quantidade");
            }

            jLabelQuantidade.setText(String.valueOf(totalQuantity));

        } catch (Exception e) {
            System.out.println("Erro ao calcular quantidade total: " + e.getMessage());
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListarMaterialArmazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListarMaterialArmazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListarMaterialArmazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListarMaterialArmazem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListarMaterialArmazem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JComboBox<String> jComboBoxIDArmazem;
    private javax.swing.JComboBox<String> jComboBoxMatrialamz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
